# Generated by Django 2.2 on 2019-04-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
