# Generated by Django 2.2 on 2019-04-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_people_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='photo',
            field=models.FileField(default='', upload_to='untitled/uploads/'),
        ),
    ]
